### ISSUE TITLE
Trouble executing ABB3 example

### ISSUE THREAD

**Issue by rjacak-invenra** [Exscientia/abodybuilder3#1]
Hi Henry/Exscientia team,

Thanks for releasing this update to ABodyBuilder.  I'm excited to start using it.  

I'm hitting an error with the first example in the included notebook (traceback below).  It happens during the torch.cat call in the forward function of the StructureModule class.  The dimensions of z_initial and the modified pairwise_distance_feature_map appear to be incompatible, but I'm unable to figure out why.  I should add I'm trying to run this with CPU-only and on a M1 Mac, so this error could be solely due to that.

```
Traceback (most recent call last):
  File "/Users/rjacak/Software/abodybuilder3/notebooks/6yio.py", line 27, in <module>
    output = model(ab_input_batch, ab_input_batch["aatype"])
  File "/Users/rjacak/Software/abodybuilder3/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/rjacak/Software/abodybuilder3/src/abodybuilder3/openfold/model/structure_module.py", line 745, in forward
    z = torch.cat(
RuntimeError: Sizes of tensors must match except in dimension 4. Expected size 229 but got size 1 for tensor number 1 in the list.
```

```
$ cat 6yio.py
import os, sys
sys.path.insert(0, os.path.abspath(os.path.join('../src')))
sys.path.insert(0, os.path.abspath(os.path.join('../src/..')))

from src.abodybuilder3.utils import string_to_input, output_to_pdb, add_atom37_to_output
from src.abodybuilder3.lightning_module import LitABB3
from src.abodybuilder3.language.model import ProtT5
import py3Dmol
import torch

heavy = "QVQLVQSGAEVKKPGSSVKVSCKASGGTFSSLAISWVRQAPGQGLEWMGGIIPIFGTANYAQKFQGRVTITADESTSTAYMELSSLRSEDTAVYYCARGGSVSGTLVDFDIWGQGTMVTVSS"
light = "DIQMTQSPSTLSASVGDRVTITCRASQSISSWLAWYQQKPGKAPKLLIYKASSLESGVPSRFSGSGSGTEFTLTISSLQPDDFATYYCQQYNIYPITFGGGTKVEIK"

module = LitABB3.load_from_checkpoint("../output/plddt-loss/best_second_stage.ckpt")
model = module.model

ab_input = string_to_input(heavy=heavy, light=light)
ab_input_batch = {
    key: value.unsqueeze(0) for key, value in ab_input.items()
} # add batch dim
output = model(ab_input_batch, ab_input_batch["aatype"])
output = add_atom37_to_output(output, ab_input["aatype"])
pdb_string = output_to_pdb(output, ab_input)
```

Any ideas?

**Comment by exs-hkenlay** [comment]
Hi @rjacak-invenra, thank you for bringing this to our attention. It seems I had made an error with the batch dimensions. The issue was that `string_to_input` returned `ab_input["single"]` and `ab_input["pair"]` with a batch dimension already, so the dictionary comprehension was adding another unnecessary dimension to these inputs. We have just pushed an update to `main`, can you please try again with the updated example?

**Comment by rjacak-invenra** [comment]
Commit 4ec2bba did the trick, can confirm it works.  Thank you!
